name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches: [ docs ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: keta1/cicool-server
          TARGET_BRANCH: page
          BUILD_SCRIPT: yarn && yarn cicool:build
          BUILD_DIR: cicool/.vuepress/dist
          CNAME: cicool.ketal.icu
